INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('1', 'Afghanistan', '1', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('2', 'Albania', '2', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('3', 'Algeria', '3', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('4', 'American Samoa', '4', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('5', 'Andorra', '5', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('6', 'Angola', '6', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('7', 'Anguilla', '7', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('8', 'Antarctica', '8', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('9', 'Antigua And Barbuda', '9', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('10', 'Argentina', '10', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('11', 'Armenia', '11', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('12', 'Aruba', '12', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('13', 'Australia', '13', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('14', 'Austria', '14', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('15', 'Azerbaijan', '15', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('16', 'Bahamas', '16', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('17', 'Bahrain', '17', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('18', 'Bangladesh', '18', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('19', 'Barbados', '19', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('20', 'Belarus', '20', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('21', 'Belgium', '21', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('22', 'Belize', '22', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('23', 'Benin', '23', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('24', 'Bermuda', '24', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('25', 'Bhutan', '25', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('26', 'Bolivia', '26', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('27', 'Bosnia and Herzegovina', '27', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('28', 'Botswana', '28', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('29', 'Bouvet Island', '29', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('30', 'Brazil', '30', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('31', 'British Indian Ocean Territory', '31', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('32', 'Brunei', '32', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('33', 'Bulgaria', '33', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('34', 'Burkina Faso', '34', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('35', 'Burundi', '35', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('36', 'Cambodia', '36', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('37', 'Cameroon', '37', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('38', 'Canada', '38', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('39', 'Cape Verde', '39', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('40', 'Cayman Islands', '40', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('41', 'Central African Republic', '41', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('42', 'Chad', '42', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('43', 'Chile', '43', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('44', 'China', '44', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('45', 'Christmas Island', '45', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('46', 'Cocos (Keeling) Islands', '46', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('47', 'Colombia', '47', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('48', 'Comoros', '48', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('49', 'Congo', '49', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('50', 'Cook Islands', '50', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('51', 'Costa Rica', '51', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('52', 'Croatia (Hrvatska)', '52', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('53', 'Cuba', '53', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('54', 'Cyprus', '54', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('55', 'Czech Republic', '55', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('56', 'Denmark', '56', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('57', 'Djibouti', '57', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('58', 'Dominica', '58', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('59', 'Dominican Republic', '59', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('60', 'East Timor', '60', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('61', 'Ecuador', '61', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('62', 'Egypt', '62', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('63', 'El Salvador', '63', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('64', 'Equatorial Guinea', '64', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('65', 'Eritrea', '65', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('66', 'Estonia', '66', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('67', 'Ethiopia', '67', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('68', 'Falkland Islands (Malvinas)', '68', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('69', 'Faroe Islands', '69', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('70', 'Fiji', '70', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('71', 'Finland', '71', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('72', 'France', '72', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('73', 'French Guiana', '73', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('74', 'French Polynesia', '74', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('75', 'French Southern Territories', '75', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('76', 'Gabon', '76', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('77', 'Gambia', '77', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('78', 'Georgia', '78', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('79', 'Germany', '79', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('80', 'Ghana', '80', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('81', 'Gibraltar', '81', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('82', 'Guernsey', '82', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('83', 'Greece', '83', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('84', 'Greenland', '84', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('85', 'Grenada', '85', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('86', 'Guadeloupe', '86', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('87', 'Guam', '87', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('88', 'Guatemala', '88', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('89', 'Guinea', '89', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('90', 'Guinea-Bissau', '90', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('91', 'Guyana', '91', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('92', 'Haiti', '92', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('93', 'Heard and Mc Donald Islands', '93', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('94', 'Honduras', '94', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('95', 'Hong Kong', '95', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('96', 'Hungary', '96', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('97', 'Iceland', '97', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('98', 'India', '98', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('99', 'Isle of Man', '99', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('100', 'Indonesia', '100', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('101', 'Iran (Islamic Republic of)', '101', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('102', 'Iraq', '102', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('103', 'Ireland', '103', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('104', 'Israel', '104', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('105', 'Italy', '105', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('106', 'Ivory Coast', '106', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('107', 'Jersey', '107', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('108', 'Jamaica', '108', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('109', 'Japan', '109', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('110', 'Jordan', '110', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('111', 'Kazakhstan', '111', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('112', 'Kenya', '112', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('113', 'Kiribati', '113', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('114', 'Korea North', '114', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('115', 'Korea South', '115', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('116', 'Kosovo', '116', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('117', 'Kuwait', '117', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('118', 'Kyrgyzstan', '118', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('119', 'Lao People''s Democratic Republic', '119', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('120', 'Latvia', '120', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('121', 'Lebanon', '121', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('122', 'Lesotho', '122', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('123', 'Liberia', '123', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('124', 'Libyan Arab Jamahiriya', '124', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('125', 'Liechtenstein', '125', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('126', 'Lithuania', '126', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('127', 'Luxembourg', '127', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('128', 'Macau', '128', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('129', 'Macedonia', '129', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('130', 'Madagascar', '130', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('131', 'Malawi', '131', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('132', 'Malaysia', '132', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('133', 'Maldives', '133', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('134', 'Mali', '134', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('135', 'Malta', '135', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('136', 'Marshall Islands', '136', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('137', 'Martinique', '137', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('138', 'Mauritania', '138', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('139', 'Mauritius', '139', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('140', 'Mayotte', '140', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('141', 'Mexico', '141', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('142', 'Micronesia, Federated States of', '142', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('143', 'Moldova, Republic of', '143', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('144', 'Monaco', '144', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('145', 'Mongolia', '145', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('146', 'Montenegro', '146', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('147', 'Montserrat', '147', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('148', 'Morocco', '148', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('149', 'Mozambique', '149', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('150', 'Myanmar', '150', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('151', 'Namibia', '151', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('152', 'Nauru', '152', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('153', 'Nepal', '153', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('154', 'Netherlands', '154', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('155', 'Netherlands Antilles', '155', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('156', 'New Caledonia', '156', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('157', 'New Zealand', '157', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('158', 'Nicaragua', '158', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('159', 'Niger', '159', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('160', 'Nigeria', '160', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('161', 'Niue', '161', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('162', 'Norfolk Island', '162', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('163', 'Northern Mariana Islands', '163', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('164', 'Norway', '164', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('165', 'Oman', '165', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('166', 'Pakistan', '166', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('167', 'Palau', '167', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('168', 'Palestine', '168', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('169', 'Panama', '169', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('170', 'Papua New Guinea', '170', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('171', 'Paraguay', '171', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('172', 'Peru', '172', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('173', 'Philippines', '173', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('174', 'Pitcairn', '174', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('175', 'Poland', '175', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('176', 'Portugal', '176', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('177', 'Puerto Rico', '177', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('178', 'Qatar', '178', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('179', 'Reunion', '179', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('180', 'Romania', '180', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('181', 'Russian Federation', '181', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('182', 'Rwanda', '182', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('183', 'Saint Kitts and Nevis', '183', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('184', 'Saint Lucia', '184', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('185', 'Saint Vincent and the Grenadines', '185', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('186', 'Samoa', '186', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('187', 'San Marino', '187', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('188', 'Sao Tome and Principe', '188', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('189', 'Saudi Arabia', '189', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('190', 'Senegal', '190', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('191', 'Serbia', '191', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('192', 'Seychelles', '192', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('193', 'Sierra Leone', '193', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('194', 'Singapore', '194', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('195', 'Slovakia', '195', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('196', 'Slovenia', '196', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('197', 'Solomon Islands', '197', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('198', 'Somalia', '198', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('199', 'South Africa', '199', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('200', 'South Georgia South Sandwich Islands', '200', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('201', 'Spain', '201', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('202', 'Sri Lanka', '202', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('203', 'St. Helena', '203', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('204', 'St. Pierre and Miquelon', '204', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('205', 'Sudan', '205', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('206', 'Suriname', '206', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('207', 'Svalbard and Jan Mayen Islands', '207', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('208', 'Swaziland', '208', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('209', 'Sweden', '209', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('210', 'Switzerland', '210', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('211', 'Syrian Arab Republic', '211', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('212', 'Taiwan', '212', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('213', 'Tajikistan', '213', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('214', 'Tanzania, United Republic of', '214', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('215', 'Thailand', '215', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('216', 'Togo', '216', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('217', 'Tokelau', '217', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('218', 'Tonga', '218', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('219', 'Trinidad and Tobago', '219', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('220', 'Tunisia', '220', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('221', 'Turkey', '221', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('222', 'Turkmenistan', '222', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('223', 'Turks and Caicos Islands', '223', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('224', 'Tuvalu', '224', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('225', 'Uganda', '225', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('226', 'Ukraine', '226', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('227', 'United Arab Emirates', '227', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('228', 'United Kingdom', '228', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('229', 'United States', '229', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('230', 'United States minor outlying islands', '230', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('231', 'Uruguay', '231', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('232', 'Uzbekistan', '232', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('233', 'Vanuatu', '233', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('234', 'Vatican City State', '234', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('235', 'Venezuela', '235', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('236', 'Vietnam', '236', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('237', 'Virgin Islands (British)', '237', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('238', 'Virgin Islands (U.S.)', '238', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('239', 'Wallis and Futuna Islands', '239', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('240', 'Western Sahara', '240', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('241', 'Yemen', '241', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('242', 'Yugoslavia', '242', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('243', 'Zaire', '243', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('244', 'Zambia', '244', '1') ;
INSERT INTO `mm__new_countries_states` (`id`, `name`, `country_id`, `active`) VALUES ('245', 'Zimbabwe', '245', '1') ;