INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('1', 'AF', 'Afghanistan', '93', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('2', 'AL', 'Albania', '355', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('3', 'DZ', 'Algeria', '213', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('4', 'AS', 'American Samoa', '1684', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('5', 'AD', 'Andorra', '376', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('6', 'AO', 'Angola', '244', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('7', 'AI', 'Anguilla', '1264', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('8', 'AQ', 'Antarctica', '0', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('9', 'AG', 'Antigua And Barbuda', '1268', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('10', 'AR', 'Argentina', '54', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('11', 'AM', 'Armenia', '374', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('12', 'AW', 'Aruba', '297', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('13', 'AU', 'Australia', '61', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('14', 'AT', 'Austria', '43', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('15', 'AZ', 'Azerbaijan', '994', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('16', 'BS', 'Bahamas', '1242', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('17', 'BH', 'Bahrain', '973', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('18', 'BD', 'Bangladesh', '880', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('19', 'BB', 'Barbados', '1246', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('20', 'BY', 'Belarus', '375', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('21', 'BE', 'Belgium', '32', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('22', 'BZ', 'Belize', '501', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('23', 'BJ', 'Benin', '229', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('24', 'BM', 'Bermuda', '1441', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('25', 'BT', 'Bhutan', '975', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('26', 'BO', 'Bolivia', '591', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('27', 'BA', 'Bosnia and Herzegovina', '387', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('28', 'BW', 'Botswana', '267', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('29', 'BV', 'Bouvet Island', '0', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('30', 'BR', 'Brazil', '55', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('31', 'IO', 'British Indian Ocean Territory', '246', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('32', 'BN', 'Brunei', '673', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('33', 'BG', 'Bulgaria', '359', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('34', 'BF', 'Burkina Faso', '226', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('35', 'BI', 'Burundi', '257', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('36', 'KH', 'Cambodia', '855', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('37', 'CM', 'Cameroon', '237', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('38', 'CA', 'Canada', '1', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('39', 'CV', 'Cape Verde', '238', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('40', 'KY', 'Cayman Islands', '1345', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('41', 'CF', 'Central African Republic', '236', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('42', 'TD', 'Chad', '235', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('43', 'CL', 'Chile', '56', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('44', 'CN', 'China', '86', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('45', 'CX', 'Christmas Island', '61', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('46', 'CC', 'Cocos (Keeling) Islands', '672', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('47', 'CO', 'Colombia', '57', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('48', 'KM', 'Comoros', '269', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('49', 'CG', 'Congo', '242', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('50', 'CK', 'Cook Islands', '682', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('51', 'CR', 'Costa Rica', '506', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('52', 'HR', 'Croatia (Hrvatska)', '385', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('53', 'CU', 'Cuba', '53', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('54', 'CY', 'Cyprus', '357', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('55', 'CZ', 'Czech Republic', '420', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('56', 'DK', 'Denmark', '45', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('57', 'DJ', 'Djibouti', '253', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('58', 'DM', 'Dominica', '1767', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('59', 'DO', 'Dominican Republic', '1809', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('60', 'TP', 'East Timor', '670', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('61', 'EC', 'Ecuador', '593', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('62', 'EG', 'Egypt', '20', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('63', 'SV', 'El Salvador', '503', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('64', 'GQ', 'Equatorial Guinea', '240', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('65', 'ER', 'Eritrea', '291', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('66', 'EE', 'Estonia', '372', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('67', 'ET', 'Ethiopia', '251', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('68', 'FK', 'Falkland Islands (Malvinas)', '500', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('69', 'FO', 'Faroe Islands', '298', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('70', 'FJ', 'Fiji', '679', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('71', 'FI', 'Finland', '358', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('72', 'FR', 'France', '33', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('73', 'GF', 'French Guiana', '594', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('74', 'PF', 'French Polynesia', '689', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('75', 'TF', 'French Southern Territories', '0', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('76', 'GA', 'Gabon', '241', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('77', 'GM', 'Gambia', '220', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('78', 'GE', 'Georgia', '995', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('79', 'DE', 'Germany', '49', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('80', 'GH', 'Ghana', '233', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('81', 'GI', 'Gibraltar', '350', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('82', 'GK', 'Guernsey', '44', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('83', 'GR', 'Greece', '30', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('84', 'GL', 'Greenland', '299', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('85', 'GD', 'Grenada', '1473', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('86', 'GP', 'Guadeloupe', '590', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('87', 'GU', 'Guam', '1671', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('88', 'GT', 'Guatemala', '502', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('89', 'GN', 'Guinea', '224', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('90', 'GW', 'Guinea-Bissau', '245', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('91', 'GY', 'Guyana', '592', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('92', 'HT', 'Haiti', '509', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('93', 'HM', 'Heard and Mc Donald Islands', '0', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('94', 'HN', 'Honduras', '504', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('95', 'HK', 'Hong Kong', '852', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('96', 'HU', 'Hungary', '36', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('97', 'IS', 'Iceland', '354', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('98', 'IN', 'India', '91', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('99', 'IM', 'Isle of Man', '44', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('100', 'ID', 'Indonesia', '62', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('101', 'IR', 'Iran (Islamic Republic of)', '98', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('102', 'IQ', 'Iraq', '964', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('103', 'IE', 'Ireland', '353', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('104', 'IL', 'Israel', '972', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('105', 'IT', 'Italy', '39', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('106', 'CI', 'Ivory Coast', '225', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('107', 'JE', 'Jersey', '44', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('108', 'JM', 'Jamaica', '1876', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('109', 'JP', 'Japan', '81', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('110', 'JO', 'Jordan', '962', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('111', 'KZ', 'Kazakhstan', '7', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('112', 'KE', 'Kenya', '254', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('113', 'KI', 'Kiribati', '686', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('114', 'KP', 'Korea North', '850', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('115', 'KR', 'Korea South', '82', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('116', 'XK', 'Kosovo', '383', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('117', 'KW', 'Kuwait', '965', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('118', 'KG', 'Kyrgyzstan', '996', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('119', 'LA', 'Lao People''s Democratic Republic', '856', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('120', 'LV', 'Latvia', '371', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('121', 'LB', 'Lebanon', '961', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('122', 'LS', 'Lesotho', '266', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('123', 'LR', 'Liberia', '231', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('124', 'LY', 'Libyan Arab Jamahiriya', '218', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('125', 'LI', 'Liechtenstein', '423', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('126', 'LT', 'Lithuania', '370', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('127', 'LU', 'Luxembourg', '352', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('128', 'MO', 'Macau', '853', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('129', 'MK', 'Macedonia', '389', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('130', 'MG', 'Madagascar', '261', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('131', 'MW', 'Malawi', '265', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('132', 'MY', 'Malaysia', '60', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('133', 'MV', 'Maldives', '960', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('134', 'ML', 'Mali', '223', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('135', 'MT', 'Malta', '356', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('136', 'MH', 'Marshall Islands', '692', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('137', 'MQ', 'Martinique', '596', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('138', 'MR', 'Mauritania', '222', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('139', 'MU', 'Mauritius', '230', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('140', 'TY', 'Mayotte', '262', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('141', 'MX', 'Mexico', '52', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('142', 'FM', 'Micronesia, Federated States of', '691', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('143', 'MD', 'Moldova, Republic of', '373', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('144', 'MC', 'Monaco', '377', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('145', 'MN', 'Mongolia', '976', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('146', 'ME', 'Montenegro', '382', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('147', 'MS', 'Montserrat', '1664', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('148', 'MA', 'Morocco', '212', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('149', 'MZ', 'Mozambique', '258', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('150', 'MM', 'Myanmar', '95', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('151', 'NA', 'Namibia', '264', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('152', 'NR', 'Nauru', '674', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('153', 'NP', 'Nepal', '977', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('154', 'NL', 'Netherlands', '31', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('155', 'AN', 'Netherlands Antilles', '599', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('156', 'NC', 'New Caledonia', '687', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('157', 'NZ', 'New Zealand', '64', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('158', 'NI', 'Nicaragua', '505', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('159', 'NE', 'Niger', '227', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('160', 'NG', 'Nigeria', '234', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('161', 'NU', 'Niue', '683', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('162', 'NF', 'Norfolk Island', '672', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('163', 'MP', 'Northern Mariana Islands', '1670', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('164', 'NO', 'Norway', '47', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('165', 'OM', 'Oman', '968', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('166', 'PK', 'Pakistan', '92', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('167', 'PW', 'Palau', '680', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('168', 'PS', 'Palestine', '970', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('169', 'PA', 'Panama', '507', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('170', 'PG', 'Papua New Guinea', '675', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('171', 'PY', 'Paraguay', '595', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('172', 'PE', 'Peru', '51', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('173', 'PH', 'Philippines', '63', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('174', 'PN', 'Pitcairn', '0', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('175', 'PL', 'Poland', '48', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('176', 'PT', 'Portugal', '351', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('177', 'PR', 'Puerto Rico', '1787', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('178', 'QA', 'Qatar', '974', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('179', 'RE', 'Reunion', '262', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('180', 'RO', 'Romania', '40', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('181', 'RU', 'Russian Federation', '70', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('182', 'RW', 'Rwanda', '250', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('183', 'KN', 'Saint Kitts and Nevis', '1869', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('184', 'LC', 'Saint Lucia', '1758', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('185', 'VC', 'Saint Vincent and the Grenadines', '1784', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('186', 'WS', 'Samoa', '684', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('187', 'SM', 'San Marino', '378', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('188', 'ST', 'Sao Tome and Principe', '239', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('189', 'SA', 'Saudi Arabia', '966', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('190', 'SN', 'Senegal', '221', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('191', 'RS', 'Serbia', '381', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('192', 'SC', 'Seychelles', '248', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('193', 'SL', 'Sierra Leone', '232', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('194', 'SG', 'Singapore', '65', '1', '1');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('195', 'SK', 'Slovakia', '421', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('196', 'SI', 'Slovenia', '386', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('197', 'SB', 'Solomon Islands', '677', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('198', 'SO', 'Somalia', '252', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('199', 'ZA', 'South Africa', '27', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('200', 'GS', 'South Georgia South Sandwich Islands', '0', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('201', 'ES', 'Spain', '34', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('202', 'LK', 'Sri Lanka', '94', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('203', 'SH', 'St. Helena', '290', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('204', 'PM', 'St. Pierre and Miquelon', '508', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('205', 'SD', 'Sudan', '249', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('206', 'SR', 'Suriname', '597', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('207', 'SJ', 'Svalbard and Jan Mayen Islands', '47', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('208', 'SZ', 'Swaziland', '268', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('209', 'SE', 'Sweden', '46', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('210', 'CH', 'Switzerland', '41', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('211', 'SY', 'Syrian Arab Republic', '963', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('212', 'TW', 'Taiwan', '886', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('213', 'TJ', 'Tajikistan', '992', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('214', 'TZ', 'Tanzania, United Republic of', '255', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('215', 'TH', 'Thailand', '66', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('216', 'TG', 'Togo', '228', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('217', 'TK', 'Tokelau', '690', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('218', 'TO', 'Tonga', '676', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('219', 'TT', 'Trinidad and Tobago', '1868', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('220', 'TN', 'Tunisia', '216', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('221', 'TR', 'Turkey', '90', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('222', 'TM', 'Turkmenistan', '7370', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('223', 'TC', 'Turks and Caicos Islands', '1649', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('224', 'TV', 'Tuvalu', '688', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('225', 'UG', 'Uganda', '256', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('226', 'UA', 'Ukraine', '380', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('227', 'AE', 'United Arab Emirates', '971', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('228', 'GB', 'United Kingdom', '44', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('229', 'US', 'United States', '1', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('230', 'UM', 'United States minor outlying islands', '1', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('231', 'UY', 'Uruguay', '598', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('232', 'UZ', 'Uzbekistan', '998', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('233', 'VU', 'Vanuatu', '678', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('234', 'VA', 'Vatican City State', '39', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('235', 'VE', 'Venezuela', '58', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('236', 'VN', 'Vietnam', '84', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('237', 'VG', 'Virgin Islands (British)', '1284', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('238', 'VI', 'Virgin Islands (U.S.)', '1340', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('239', 'WF', 'Wallis and Futuna Islands', '681', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('240', 'EH', 'Western Sahara', '212', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('241', 'YE', 'Yemen', '967', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('242', 'YU', 'Yugoslavia', '38', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('243', 'ZR', 'Zaire', '243', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('244', 'ZM', 'Zambia', '260', '1', '2');
INSERT INTO `mm__new_countries` (`id`, `sortname`, `name`, `phonecode`, `active`, `sort`) VALUES ('245', 'ZW', 'Zimbabwe', '263', '1', '2');